version: '3.2'
services:

    postgres:
        container_name: kf-postgres
        image: postgres
        ports:
            - "5432:5432"
        restart: always
        environment:
            POSTGRES_PASSWORD: password
        networks:
            - backend
      
    api:
        container_name: kf-api
        build: ./Service/Rest
        ports:
            - "3000:3000"
        restart: always
        networks:
            - backend
        depends_on: 
            - postgres

    ui:
        container_name: kf-ui
        build: ./UI/nginx
        ports:
            - "80:80"
        restart: always
        networks:
            - frontend
        depends_on: 
            - api
            
    # ui:
        # container_name: kf-ui
        # build: ./UI
        # ports:
            # - "80:4200"
        # restart: always
        # networks:
            # - frontend
        # depends_on: 
            # - api

networks:
  frontend:
  backend: